---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gcp-backend-service-exporter
  labels:
    app.kubernetes.io/name: gcp-backend-service-exporter
  namespace: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gcp-backend-service-exporter
  labels:
    app.kubernetes.io/name: gcp-backend-service-exporter
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gcp-backend-service-exporter
  labels:
    app.kubernetes.io/name: gcp-backend-service-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gcp-backend-service-exporter
subjects:
- kind: ServiceAccount
  name: gcp-backend-service-exporter
  namespace: monitoring

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-backend-service-exporter
  labels:
    app.kubernetes.io/name: gcp-backend-service-exporter
  namespace: monitoring
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: gcp-backend-service-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gcp-backend-service-exporter
    spec:
      serviceAccountName: gcp-backend-service-exporter
      containers:
      - name: gcp-backend-service-exporter
        image: <current_image>
        ports:
        - name: metrics
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8080
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 1
            memory: 200Mi
          requests:
            cpu: 20m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
